# data-hub:

*   [Website](https://data-hub.ir/)
*   [Youtube](https://www.youtube.com/channel/UCrBcbQWcD0ortWqHAlP94ug)
*   [Github](https://github.com/datahub-ir)
*   Telegram Channel: @**data_hub_ir**
*   Telegram Group:    **@data_jobs**

NumPy’s main object is the homogeneous multidimensional array. 
It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

In [1]:
!python --version

Python 3.9.6


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip show numpy

Name: numpy
Version: 1.20.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\mohammad\appdata\local\programs\python\python39\lib\site-packages
Requires: 
Required-by: blis, cufflinks, gensim, h5py, Keras-Preprocessing, lightgbm, matplotlib, mittens, mizani, nlpaug, numba, numexpr, opt-einsum, pandas, patsy, plotnine, pyLDAvis, scikit-learn, scipy, seaborn, spacy, statsmodels, tensorboard, tensorflow, textaugment, thinc, torchvision, transformers, umap-learn, xgboost
Note: you may need to restart the kernel to use updated packages.


## نحوه فراخوانی

In [4]:
import numpy as np

## تعریف آرایه

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.array([[1, ], [3, 4]])

C:\Users\Mohammad\AppData\Local\Temp/ipykernel_9096/2041976787.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, ], [3, 4]])


array([list([1]), list([3, 4])], dtype=object)

In [8]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [10]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [11]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## بروزرسانی

In [12]:
a

array([1, 2, 3])

In [13]:
a[2] = 30
a

array([ 1,  2, 30])

In [14]:
a[0:3] = 12
a

array([12, 12, 12])

## تغییر ابعاد

In [15]:
b = np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
b.reshape(10,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## ابعاد آرایه

In [17]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr = np.arange(1,10)
arr.ndim

1

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
len(arr)

9

In [21]:
arr.shape

(9,)

In [22]:
arr.size

9

In [23]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
b.ndim

2

In [25]:
b.shape

(2, 3)

In [26]:
b.shape[0]

2

In [27]:
b.shape[1]

3

In [28]:
b.size

6

## تبدیل لیست به آرایه

In [29]:
list2d = [[1,2,3],[4,5,6]]
arr2d = np.asarray(list2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

## آرایه هایی با مقادیر ثابت

In [30]:
listzeros = np.zeros((3,4), dtype='int32')
listzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
listones = np.ones((2,2), dtype='int8')
listones

array([[1, 1],
       [1, 1]], dtype=int8)

In [32]:
listfull = np.full((5,3), 6)
listfull 

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [33]:
listeye = np.eye(3)
listeye 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.linspace(1, 4, num=8)

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [35]:
test = np.linspace(1.0, 4.0, num=20)
test

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [36]:
rarr = np.random.random((3,4))
rarr*100

array([[33.92008153, 73.74936013,  3.20452195, 78.85648484],
       [38.50643378, 17.98398106,  5.9804054 , 79.60508872],
       [94.44248151, 47.29323198,  6.41824269, 82.35231648]])

## توابع آماده

<h3 dir='rtl'>توابع آماری کتابخانه NumPy</h3>

<div dir='rtl'>

<ul>
<li><code>min</code>:محاسبه کمینه مقادیر </li>
<li><code>max</code>:محاسبه بیشینه مقادیر </li>
<li><code>mean</code>: محاسبه میانگین مقادیر </li>
<li><code>median</code>: محاسبه میانه مقادیر </li>
<li><code>std</code>:محاسبه انحراف معیار مقادیر</li>
</ul>
    
    
</div>

In [37]:
rarr

array([[0.33920082, 0.7374936 , 0.03204522, 0.78856485],
       [0.38506434, 0.17983981, 0.05980405, 0.79605089],
       [0.94442482, 0.47293232, 0.06418243, 0.82352316]])

In [38]:
np.max(rarr, axis=0)

array([0.94442482, 0.7374936 , 0.06418243, 0.82352316])

In [39]:
np.argmax(rarr, axis=0)

array([2, 0, 2, 2], dtype=int64)

In [40]:
np.min(rarr, axis=1)

array([0.03204522, 0.05980405, 0.06418243])

In [41]:
np.argmin(rarr, axis=1)

array([2, 2, 2], dtype=int64)

In [42]:
np.mean(rarr, axis=1)

array([0.47432612, 0.35518977, 0.57626568])

In [43]:
np.mean(rarr)

0.4685938583882097

In [44]:
np.median(rarr, axis=1)

array([0.53834721, 0.28245207, 0.64822774])

In [45]:
rarr.sum(axis=0)

array([1.66868997, 1.39026573, 0.1560317 , 2.4081389 ])

In [46]:
rarr.sum()

5.623126300658517

## ایندکس ها

In [47]:
rarr

array([[0.33920082, 0.7374936 , 0.03204522, 0.78856485],
       [0.38506434, 0.17983981, 0.05980405, 0.79605089],
       [0.94442482, 0.47293232, 0.06418243, 0.82352316]])

In [48]:
rarr[1,2]

0.059804053987353445

In [49]:
rarr[0:2,:]

array([[0.33920082, 0.7374936 , 0.03204522, 0.78856485],
       [0.38506434, 0.17983981, 0.05980405, 0.79605089]])

In [50]:
rarr[:,1:]

array([[0.7374936 , 0.03204522, 0.78856485],
       [0.17983981, 0.05980405, 0.79605089],
       [0.47293232, 0.06418243, 0.82352316]])

In [51]:
rarr[:-1,:]

array([[0.33920082, 0.7374936 , 0.03204522, 0.78856485],
       [0.38506434, 0.17983981, 0.05980405, 0.79605089]])

In [52]:
rarr[:,:-2]

array([[0.33920082, 0.7374936 ],
       [0.38506434, 0.17983981],
       [0.94442482, 0.47293232]])

In [53]:
for row in rarr:
    print(row)

[0.33920082 0.7374936  0.03204522 0.78856485]
[0.38506434 0.17983981 0.05980405 0.79605089]
[0.94442482 0.47293232 0.06418243 0.82352316]


In [54]:
for row in rarr.flat:
    print(row)

0.33920081529015655
0.7374936012749171
0.032045219513685996
0.7885648483870896
0.38506433781665494
0.17983981057262466
0.059804053987353445
0.7960508872110953
0.9444248150691105
0.4729323197896441
0.06418242689681364
0.8235231648493714


In [55]:
for i in rarr:
    print(i**(1/3.))

[0.69740592 0.90348182 0.31762968 0.92387342]
[0.72751916 0.56445407 0.39106013 0.92678773]
[0.98112076 0.77911159 0.4003797  0.93732875]


## توابع ریاضی

In [56]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [57]:
x

array([[1., 2.],
       [3., 4.]])

In [58]:
y

array([[5., 6.],
       [7., 8.]])

In [59]:
x.T

array([[1., 3.],
       [2., 4.]])

In [60]:
x > 2

array([[False, False],
       [ True,  True]])

In [61]:
x[x > 2]

array([3., 4.])

In [62]:
x - 2

array([[-1.,  0.],
       [ 1.,  2.]])

In [63]:
x * y

array([[ 5., 12.],
       [21., 32.]])

In [64]:
10 * np.sin(x)

array([[ 8.41470985,  9.09297427],
       [ 1.41120008, -7.56802495]])

In [65]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [66]:
v = x.flatten()
w = y.flatten()

In [67]:
v

array([1., 2., 3., 4.])

In [68]:
w

array([5., 6., 7., 8.])

In [69]:
v.dot(w)

70.0

In [70]:
np.dot(v, w)

70.0

In [71]:
x

array([[1., 2.],
       [3., 4.]])

In [72]:
y

array([[5., 6.],
       [7., 8.]])

In [73]:
np.matmul(x, y)

array([[19., 22.],
       [43., 50.]])

In [74]:
np.linalg.det(x)

-2.0000000000000004

## ترکیب

In [75]:
x

array([[1., 2.],
       [3., 4.]])

In [76]:
y

array([[5., 6.],
       [7., 8.]])

In [77]:
np.vstack((x, y))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [78]:
np.hstack((x, y))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])