NumPy’s main object is the homogeneous multidimensional array. 
It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

<div dir='rtl'> NumPy برای آرایه های چند بعدی و ضرب ماتریس بسیار مناسب است.</div>

In [1]:
#!pip install numpy

## نحوه فراخوانی

In [2]:
import numpy as np

## تعریف آرایه

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.array([[1, ], [3, 4]])

C:\Users\Mohammad\AppData\Local\Temp/ipykernel_13352/2041976787.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, ], [3, 4]])


array([list([1]), list([3, 4])], dtype=object)

In [6]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [8]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [9]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## بروزرسانی

In [10]:
a

array([1, 2, 3])

In [11]:
a[2] = 30
a

array([ 1,  2, 30])

In [12]:
a[0:3] = 12
a

array([12, 12, 12])

## تغییر ابعاد

In [13]:
b = np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
b.reshape(10,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## ابعاد آرایه

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.arange(1,10)
arr.ndim

1

In [17]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
len(arr)

9

In [19]:
arr.shape

(9,)

In [20]:
arr.size

9

In [21]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
b.ndim

2

In [23]:
b.shape

(2, 3)

In [24]:
b.shape[0]

2

In [25]:
b.shape[1]

3

In [26]:
b.size

6

## تبدیل لیست به آرایه

In [27]:
list2d = [[1,2,3],[4,5,6]]
arr2d = np.asarray(list2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

## آرایه هایی با مقادیر ثابت

In [28]:
listzeros = np.zeros((3,4), dtype='int32')
listzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
listones = np.ones((2,2), dtype='int8')
listones

array([[1, 1],
       [1, 1]], dtype=int8)

In [30]:
listfull = np.full((5,3), 6)
listfull 

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [31]:
listeye = np.eye(3)
listeye 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.linspace(1, 4, num=8)

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [33]:
test = np.linspace(1.0, 4.0, num=20)
test

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [34]:
rarr = np.random.random((3,4))
rarr*100

array([[81.97345354,  7.86501786, 32.86972235, 87.43783479],
       [69.11308545, 75.42096775, 33.37878153, 16.80125194],
       [ 8.1918213 , 25.07134682, 45.81861345,  9.71062426]])

## توابع آماده

<h3 dir='rtl'>توابع آماری کتابخانه NumPy</h3>

<div dir='rtl'>

<ul>
<li><code>min</code>:محاسبه کمینه مقادیر </li>
<li><code>max</code>:محاسبه بیشینه مقادیر </li>
<li><code>mean</code>: محاسبه میانگین مقادیر </li>
<li><code>median</code>: محاسبه میانه مقادیر </li>
<li><code>std</code>:محاسبه انحراف معیار مقادیر</li>
</ul>
    
    
</div>

In [35]:
rarr

array([[0.81973454, 0.07865018, 0.32869722, 0.87437835],
       [0.69113085, 0.75420968, 0.33378782, 0.16801252],
       [0.08191821, 0.25071347, 0.45818613, 0.09710624]])

In [36]:
np.max(rarr, axis=0)

array([0.81973454, 0.75420968, 0.45818613, 0.87437835])

In [37]:
np.argmax(rarr, axis=0)

array([0, 1, 2, 0], dtype=int64)

In [38]:
np.min(rarr, axis=1)

array([0.07865018, 0.16801252, 0.08191821])

In [39]:
np.argmin(rarr, axis=1)

array([1, 3, 0], dtype=int64)

In [40]:
np.mean(rarr, axis=1)

array([0.52536507, 0.48678522, 0.22198101])

In [41]:
np.mean(rarr)

0.4113771008714647

In [42]:
np.median(rarr, axis=1)

array([0.57421588, 0.51245933, 0.17390986])

In [43]:
rarr.sum(axis=0)

array([1.5927836 , 1.08357332, 1.12067117, 1.13949711])

In [44]:
rarr.sum()

4.936525210457576

## ایندکس ها

In [45]:
rarr

array([[0.81973454, 0.07865018, 0.32869722, 0.87437835],
       [0.69113085, 0.75420968, 0.33378782, 0.16801252],
       [0.08191821, 0.25071347, 0.45818613, 0.09710624]])

In [46]:
rarr[1,2]

0.33378781530256363

In [47]:
rarr[0:2,:]

array([[0.81973454, 0.07865018, 0.32869722, 0.87437835],
       [0.69113085, 0.75420968, 0.33378782, 0.16801252]])

In [48]:
rarr[:,1:]

array([[0.07865018, 0.32869722, 0.87437835],
       [0.75420968, 0.33378782, 0.16801252],
       [0.25071347, 0.45818613, 0.09710624]])

In [49]:
rarr[:-1,:]

array([[0.81973454, 0.07865018, 0.32869722, 0.87437835],
       [0.69113085, 0.75420968, 0.33378782, 0.16801252]])

In [50]:
rarr[:,:-2]

array([[0.81973454, 0.07865018],
       [0.69113085, 0.75420968],
       [0.08191821, 0.25071347]])

In [51]:
for row in rarr:
    print(row)

[0.81973454 0.07865018 0.32869722 0.87437835]
[0.69113085 0.75420968 0.33378782 0.16801252]
[0.08191821 0.25071347 0.45818613 0.09710624]


In [52]:
for row in rarr.flat:
    print(row)

0.8197345353971491
0.07865017860811263
0.328697223450804
0.8743783479006815
0.6911308545274701
0.7542096774619346
0.33378781530256363
0.1680125194179971
0.08191821301613633
0.25071346822399154
0.4581861345197845
0.09710624263095236


In [53]:
for i in rarr:
    print(i**(1/3.))

[0.93588915 0.42844976 0.69013176 0.95623903]
[0.88413808 0.91025701 0.69367625 0.55179854]
[0.43430366 0.63055923 0.77092829 0.45963778]


## توابع ریاضی

In [54]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [55]:
x

array([[1., 2.],
       [3., 4.]])

In [56]:
y

array([[5., 6.],
       [7., 8.]])

In [57]:
x.T

array([[1., 3.],
       [2., 4.]])

In [58]:
x > 2

array([[False, False],
       [ True,  True]])

In [59]:
x[x > 2]

array([3., 4.])

In [60]:
x - 2

array([[-1.,  0.],
       [ 1.,  2.]])

In [61]:
x * y

array([[ 5., 12.],
       [21., 32.]])

In [62]:
10 * np.sin(x)

array([[ 8.41470985,  9.09297427],
       [ 1.41120008, -7.56802495]])

In [63]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [64]:
v = x.flatten()
w = y.flatten()

In [65]:
v

array([1., 2., 3., 4.])

In [66]:
w

array([5., 6., 7., 8.])

In [67]:
v.dot(w)

70.0

In [68]:
np.dot(v, w)

70.0

In [69]:
x

array([[1., 2.],
       [3., 4.]])

In [70]:
y

array([[5., 6.],
       [7., 8.]])

In [71]:
np.matmul(x, y)

array([[19., 22.],
       [43., 50.]])

In [72]:
np.linalg.det(x)

-2.0000000000000004

## ترکیب

In [73]:
x

array([[1., 2.],
       [3., 4.]])

In [74]:
y

array([[5., 6.],
       [7., 8.]])

In [75]:
np.vstack((x, y))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [76]:
np.hstack((x, y))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])