<div id="section1"   dir='rtl'>
    <h2>
    توجه
    </h2>
        <hr>
بخش زیادی از این فایل آموزشی مربوط به مسابقه دیتادیز است و حاصل زحمات آن ها می باشد.
</div>



# data-hub:

*   [Website](https://data-hub.ir/)
*   [Youtube](https://www.youtube.com/channel/UCrBcbQWcD0ortWqHAlP94ug)
*   [Github](https://github.com/datahub-ir)
*   Telegram Channel: @**data_hub_ir**
*   Instagram Page: @**data_hub_ir**
*   Telegram Group:    @**data_jobs**

<div id="section1"   dir='rtl'>
    <h2>
    بارگیری و کاوش داده‌ها
    </h2>
        <hr>
        در این دفترچه با مجموعه داده کوچکی به نام 
        <code>property_data.csv</code>
        که در کنار دفترچه آمده است کار می‌کنیم. برای خواندن آن از کتابخانۀ 
        <code>pandas</code>
        و برای برخی اعمال که بر روی این مجموعه داده قرار است انجام دهیم از کتابخانۀ 
        <code>numpy</code>
        استفاده می‌کنیم.
</div>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('property_data.csv')
df

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

<div dir="rtl">
یکی از کار‌های سریع و مفیدی که لازم است انجام دهیم این است که با استفاده از تابع 
        <code>head</code>
     کتابخانۀ
        <code>pandas</code>
        محتویات داخل مجموعه داده شامل اسم ستون‌ها و چند سطر اول آن را ببینیم. همچنین با استفاده از تابع
        <code>dtypes</code>
        نوع داده‌های هر ستون را مشاهده کنیم.
</div>

In [3]:
df.tail(1)

PID  ST_NUM  ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
8  100009000.0   215.0  TREMONT            Y           na        2  1800

In [4]:
df.dtypes # برگرداندن نوع ستون ها

PID             float64
ST_NUM          float64
ST_NAME          object
OWN_OCCUPIED     object
NUM_BEDROOMS     object
NUM_BATH         object
SQ_FT            object
dtype: object

<div dir='rtl'>
        حال با استفاده از اطلاعاتی که بدست آوردیم می‌توانیم بفهمیم که ستون‌های ما به چه معنا هستند و مقداری که انتظار داریم در مجموعه‌ی داده برای آن‌ها ببینیم چیست. به طور مثال:
        <ul>
            <li>
                <code>ST_NUM</code>: شماره خیابان، Numeric type
           </li>
            <li>
                <code>ST_NAME</code>: نام خیابان، string 
            </li>
                        <li>
                            <code>OWN_OCCUPIED</code>:  کسی در خانه زندگی می‌کند یا خیر؟، 'Y': بله، 'N': خیر         
            </li>
                                    <li>
                                        <code>NUM_BEDROOMS</code>: تعداد اتاق خواب‌ها، Numeric type
           </li>
        </ul>
        چیزی که متوجه‌اش می‌شویم این است که برخی انتظارات ما با چیزی که 
        <code>dtypes</code>
        می‌گوید سازگار نیست و این بدین معنا است که برخی مقادیر از آن ستون‌ها با چیزی به غیر از نوع دلخواه پر شده است که باید آن‌ها را پاک‌سازی کنیم.
        <br>
        نوع دیگر مقادیری که باید پاک‌سازی کنیم 
        <code>NaN</code>
        ها هستند. وجود
        <code>NaN</code>
        به این معنا است که داده در آن ویژگی مقداری نگرفته است.
</div>

<div id="section1"   dir='rtl'>

<h2>
    مقادیر گم‌شده
    </h2>
        <hr>
   ابتدا راه‌کار‌هایی را مطرح می‌کنیم که مجموعه داده را از مقادیر 
        <code>NaN</code>
        پاک‌سازی کند.
        <br>
        برای انجام این کار می‌توان از توابع <code>()fillna</code> یا <code>()dropna</code> بهره جست.
</div>

In [5]:
df

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [6]:
dropped_df = df.dropna() # هستند را حذف می کند Nan تمامی سطرهایی که شامل
dropped_df

PID  ST_NUM    ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y            3        1  1000
1  100002000.0   197.0  LEXINGTON            N            3      1.5    --
8  100009000.0   215.0    TREMONT            Y           na        2  1800

In [7]:
dropped_df = df.dropna(how='all')
dropped_df

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [8]:
dropped_df = df.dropna(axis=1)  # هستند را حذف می کند Nan تمامی ستون هایی که شامل
dropped_df

ST_NAME
0      PUTNAM
1   LEXINGTON
2   LEXINGTON
3    BERKELEY
4    BERKELEY
5    BERKELEY
6  WASHINGTON
7     TREMONT
8     TREMONT

In [9]:
int(df.shape[1] * .9)

6

In [10]:
# ستون هایی که کمتر از ۹۰ درصد داده سالم دارند را حذف می کند
dropped_df = df.dropna(thresh=int(df.shape[0] * .9), axis=1)
dropped_df

PID     ST_NAME OWN_OCCUPIED NUM_BATH SQ_FT
0  100001000.0      PUTNAM            Y        1  1000
1  100002000.0   LEXINGTON            N      1.5    --
2  100003000.0   LEXINGTON            N        1   850
3  100004000.0    BERKELEY           12      NaN   700
4          NaN    BERKELEY            Y        2  1600
5  100006000.0    BERKELEY            Y        1   800
6  100007000.0  WASHINGTON          NaN   HURLEY   950
7  100008000.0     TREMONT            Y        1   NaN
8  100009000.0     TREMONT            Y        2  1800

In [11]:
dropped_df = df.dropna(thresh=int(df.shape[1] * .9), axis=0)
dropped_df

PID  ST_NUM    ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y            3        1  1000
1  100002000.0   197.0  LEXINGTON            N            3      1.5    --
3  100004000.0   201.0   BERKELEY           12            1      NaN   700
4          NaN   203.0   BERKELEY            Y            3        2  1600
5  100006000.0   207.0   BERKELEY            Y          NaN        1   800
7  100008000.0   213.0    TREMONT            Y            1        1   NaN
8  100009000.0   215.0    TREMONT            Y           na        2  1800

<div dir="rtl">
        برای پر کردن داده‌هایی که مقدار 
        <code>NaN</code>
        گرفته‌اند، ابتدا باید ستون این داده‌ها را مشخص کنیم و سپس باید با مقادیری که با توجه به مسئله‌ای که با آن سر و کار داریم توجیه پذیر است، آن‌ها را مقداردهی کنیم.
</div>

In [12]:
# برمیگرداند False وگرنه True داشته باشد Nan مقدار 'ST_NUM' اگر سطر
df['ST_NUM'].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
Name: ST_NUM, dtype: bool

In [13]:
df['ST_NAME'].isnull().sum()

0

In [14]:
df['ST_NUM'].isnull().sum()

2

In [15]:
df.columns

Index(['PID', 'ST_NUM', 'ST_NAME', 'OWN_OCCUPIED', 'NUM_BEDROOMS', 'NUM_BATH',
       'SQ_FT'],
      dtype='object')

In [16]:
df

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [17]:
df['ST_NAME'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: ST_NAME, dtype: bool

In [18]:
np.array(df['ST_NAME'].isnull())

array([False, False, False, False, False, False, False, False, False])

In [19]:
column_names = df.columns
Nan_columns = list()

for col in column_names:
    if(True in np.array(df[col].isnull())):
        Nan_columns.append(col)
        
Nan_columns

['PID', 'ST_NUM', 'OWN_OCCUPIED', 'NUM_BEDROOMS', 'NUM_BATH', 'SQ_FT']

<div  dir="rtl">
حال می‌توانیم هر یک از ستون‌هایی که دارای مقدار 
        <code>NaN</code>
        هستند را به شکل مناسبی مقداردهی کنیم:
</div>

In [20]:
df['SQ_FT'] = df['SQ_FT'].fillna(800) # را با ۱۰ پر می کند 'ST_NUM' ستون Nan مقدار
df

PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   800
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [21]:
# را با میانگین ستون پر میکند Nan مقادیر
df['ST_NUM'] = df['ST_NUM'].fillna(df['ST_NUM'].mean())
df

PID      ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH  \
0  100001000.0  104.000000      PUTNAM            Y            3        1   
1  100002000.0  197.000000   LEXINGTON            N            3      1.5   
2  100003000.0  191.428571   LEXINGTON            N          NaN        1   
3  100004000.0  201.000000    BERKELEY           12            1      NaN   
4          NaN  203.000000    BERKELEY            Y            3        2   
5  100006000.0  207.000000    BERKELEY            Y          NaN        1   
6  100007000.0  191.428571  WASHINGTON          NaN            2   HURLEY   
7  100008000.0  213.000000     TREMONT            Y            1        1   
8  100009000.0  215.000000     TREMONT            Y           na        2   

  SQ_FT  
0  1000  
1    --  
2   850  
3   700  
4  1600  
5   800  
6   950  
7   800  
8  1800

<div dir="rtl">
        حال که بلدیم با داده‌های <code>NaN</code> چه کنیم، به راهکار پاک‌سازی داده‌هایی که با type ‌موردنظر ستون سازگار نیستند می‌پردازیم.
        <br>
        راهکار کلی به این شکل است که ابتدا باید این داده‌ها را در هر ستون شناسایی کنیم، سپس به جای آن‌های 
        <code>NaN</code>
        قرار دهیم و در نهایت عملیات‌هایی که برای پاک‌سازی NaN در بالا توضیح دادیم را انجام دهیم.
</div>

In [22]:
len(df['NUM_BATH'])

9

In [23]:
for i in range(len(df['NUM_BATH'])):
    try:
        int(df['NUM_BATH'][i]) # نوع ستون مدنظر
    except ValueError:
        df.loc[i, 'NUM_BATH'] = np.nan # Nan جایگزینی با
        
df

PID      ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH  \
0  100001000.0  104.000000      PUTNAM            Y            3        1   
1  100002000.0  197.000000   LEXINGTON            N            3      NaN   
2  100003000.0  191.428571   LEXINGTON            N          NaN        1   
3  100004000.0  201.000000    BERKELEY           12            1      NaN   
4          NaN  203.000000    BERKELEY            Y            3        2   
5  100006000.0  207.000000    BERKELEY            Y          NaN        1   
6  100007000.0  191.428571  WASHINGTON          NaN            2      NaN   
7  100008000.0  213.000000     TREMONT            Y            1        1   
8  100009000.0  215.000000     TREMONT            Y           na        2   

  SQ_FT  
0  1000  
1    --  
2   850  
3   700  
4  1600  
5   800  
6   950  
7   800  
8  1800

In [24]:
int(df['NUM_BATH'][6])

ValueError: cannot convert float NaN to integer

<div dir="rtl">
        روش دیگر آن است که این مقادیر اشتباه را از قبل خودمان مشخص کنیم و در هنگام خواندن از فایل
        <code>csv</code> به جای آن‌ها <code>NaN</code> قرار دهیم.
        <br>
        به طور مثال:
</div>

In [25]:
missing_values = ["n/a", "na", "--", "HURLEY"]
new_df = pd.read_csv('property_data.csv', na_values=missing_values)
new_df

PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH  \
0  100001000.0   104.0      PUTNAM            Y           3.0       1.0   
1  100002000.0   197.0   LEXINGTON            N           3.0       1.5   
2  100003000.0     NaN   LEXINGTON            N           NaN       1.0   
3  100004000.0   201.0    BERKELEY           12           1.0       NaN   
4          NaN   203.0    BERKELEY            Y           3.0       2.0   
5  100006000.0   207.0    BERKELEY            Y           NaN       1.0   
6  100007000.0     NaN  WASHINGTON          NaN           2.0       NaN   
7  100008000.0   213.0     TREMONT            Y           1.0       1.0   
8  100009000.0   215.0     TREMONT            Y           NaN       2.0   

    SQ_FT  
0  1000.0  
1     NaN  
2   850.0  
3   700.0  
4  1600.0  
5   800.0  
6   950.0  
7     NaN  
8  1800.0

In [26]:
new_df.dtypes

PID             float64
ST_NUM          float64
ST_NAME          object
OWN_OCCUPIED     object
NUM_BEDROOMS    float64
NUM_BATH        float64
SQ_FT           float64
dtype: object

<div id="section1"   dir="rtl">
<h2>
    Assert: کارهایی را که انجام دادید، تست کنید
    </h2>
        <hr>
   با استفاده از تابع 
         <code>assert</code>
        پایتون می‌توانیم به سادگی شروطی بر روی مقادیر ستون‌ها قرار دهیم و اگر مجموعۀ داده در شرط موردنظر صدق نکند، این تابع از اجرای ادامه برنامه جلوگیری می‌کند. به طور مثال با توجه به عملیات انجام شده در بالا نباید ستون ST_NUM
        مجموعه داده <code>df</code>
        مقدار <code>NaN</code>
        داشته باشد.
</div>

In [27]:
assert(df['ST_NUM'] is not np.nan)
assert(df['PID'] is not np.nan)

<div id="section1"   dir="rtl">
<h2>
            پیش‌پردازش با sklearn
    </h2>
		<p></p>
		<hr>
        مدل‌ها برای کار نیازمند داده به عنوان ورودی هستند. بنابراین باید داده‌ها را به صورت متناسب با نوع ورودی آن‌ها دربیاوریم. برای این کار از پکیج  <code>preprocessing</code>  استفاده می‌کنیم.
</div>

In [28]:
from sklearn import preprocessing

In [29]:
ary_int = np.random.randint(-100, 100, 10)
ary_int

array([ 71,  50, -86,  64, -90, -78, -78,   3, -63, -21])

In [30]:
ary_str = ['foo', 'bar', 'baz', 'x', 'y', 'z', 'z', 'z']
ary_str

['foo', 'bar', 'baz', 'x', 'y', 'z', 'z', 'z']

<div   dir='rtl'>

زمانی که با داده‌های متنی کار می‌کنیم، ممکن است همه داده‌ها عددی نباشند و مثلا داده‌های بعضی ستون‌ها به شکل طبقه‌بندی(<code>categorical</code>) باشند. ما باید آن‌ها را نیز به صورت عددی دربیاوریم چرا که اکثر مدل‌ها در <code>sklearn</code> انتظار دارند داده‌های عددی به عنوان ورودی دریافت کنند. یکی از راه‌‌های کد کردن داده‌های طبقه‌بندی استفاده از <code>labelEncoder</code> است. <code>labelEncoder</code> بازای هر دسته موجود در ورودی، یک عدد از صفر تا تعداد دسته‌ی ورودی منهای یک اختصاص می‌دهد.
</div>

In [31]:
l_encoder = preprocessing.LabelEncoder()
l_encoder.fit_transform(ary_str)

array([2, 0, 1, 3, 4, 5, 5, 5], dtype=int64)

In [32]:
ary_str

['foo', 'bar', 'baz', 'x', 'y', 'z', 'z', 'z']

In [33]:
print(l_encoder.transform(['foo']))
print(l_encoder.transform(['baz']))
print(l_encoder.transform(['bar']))

[2]
[1]
[0]


<div dir='rtl'>
        همان‌طور که می‌بینید اعداد اختصاص داده‌شده به برچسب‌ها در این حالت بدون‌ترتیب هستند. در مثال بالا <code>foo</code> قبل از <code>baz</code> آمده اما عدد اختصاص داده‌شده به آن بیشتر است.
        در صورتی که تعداد دسته‌هایی که کد می‌کنیم زیاد باشد ممکن است بخواهیم این نگاشت را به صورت یک دیکشنری داشته باشیم.

</div>

In [34]:
list(l_encoder.classes_)

['bar', 'baz', 'foo', 'x', 'y', 'z']

In [35]:
dict(zip(l_encoder.classes_, l_encoder.transform(l_encoder.classes_)))

{'bar': 0, 'baz': 1, 'foo': 2, 'x': 3, 'y': 4, 'z': 5}

<div dir='rtl'>
        کار با  <code>DataFrame</code>  از این هم ساده‌تر است! تنها چیزی که نیاز داریم این است که از متد <code>()apply.</code> برای اعمال <code>labelEncoder</code> به  <code>DataFrame</code>  استفاده کنیم. در این صورت مقادیر هر ستون به صورت جداگانه کد می‌شوند.
برای مثال دقت کنید که <code>foo</code> در ستون اول همانند <code>y</code> در ستون دوم به ۱ نگاشته می‌شود.
</div>

In [36]:
l_encoder = preprocessing.LabelEncoder()
df = pd.DataFrame(data = {'col1': ['foo','bar','foo','bar'],
                          'col2': ['x', 'y', 'x', 'z'], 
                          'col3': [3000, 20, 3000, 400]})

In [37]:
df

col1 col2  col3
0  foo    x  3000
1  bar    y    20
2  foo    x  3000
3  bar    z   400

In [38]:
df['col1'] = l_encoder.fit_transform(df['col1'])
df

col1 col2  col3
0     1    x  3000
1     0    y    20
2     1    x  3000
3     0    z   400

In [39]:
df.apply(l_encoder.fit_transform)

col1  col2  col3
0     1     0     2
1     0     1     0
2     1     0     2
3     0     2     1

<div   dir='rtl'>
      <div dir='rtl'>روش دیگری که به معرفی آن می‌پردازیم. روش <code>onehot</code> است. بسیاری از مدل‌هایی که با آن‌ها کار می‌کنیم از معیار فاصله برای حل مسائل استفاده می‌کنند. برای مثال در مسئله‌ي دسته‌بندی به روش <code>KNN</code> به دنبال نزدیک‌ترین همسایه‌ها به داده‌ی مورد نظر هستیم. 
<br>
فاصله در رابطه با داده‌های طبقه‌بندی شده معنی خود را از دست می‌دهد. برای مثال فرض کنید یکی از ویژگی‌های ما برند خودرو است. برندهای داده‌ها از سه دسته‌ی 
          <code dir="ltr">['benz', 'bmw', 'saipa']</code>
          هستند. اگر به این داده‌ها برچسب‌های ۰، ۱و ۲ را اختصاص دهیم به صورت ضمنی این معنی را به مسئله القا کردیم که فاصله‌ی بنز با سایپا بیشتر از فاصلۀ بنز با بی‌ام‌و است (فرض بدی هم نیست!) و فاصلۀ بی‌ام‌و و سایپا همانند فاصله‌ی بنز و بی‌ام‌و است (این یکی بی‌انصافی است!) بنابراین باید به دنبال راهی باشیم که در آن  فاصلۀ کد تولید شده برای این سه برند مساوی باشد.
<br>
<code>onehot</code>  روشی است که این امکان را برای ما فراهم می‌کند. در این روش بازای ورودی یک آرایه به طول تعداد کلاس‌های آن ورودی در نظر می‌گیریم. بازای هر دسته تمامی درایه‌های این آرایه‌ی جدید را برابر صفر قرار می‌دهیم و تنها درایه‌ای را که مربوط به کلاس آن دسته است را یک می‌کنیم. شکل زیر مثالی از این نحوه‌ی کدکردن را نشان می‌دهد.
<br>
    <img src="https://miro.medium.com/proxy/1*WXpoiS7HXRC-uwJPYsy1Dg.png" alt="" />
    <caption><a href='https://blog.myyellowroad.com/'>https://blog.myyellowroad.com/</a></caption>
</div>
</div>

In [40]:
df

col1 col2  col3
0     1    x  3000
1     0    y    20
2     1    x  3000
3     0    z   400

In [41]:
pd.get_dummies(df)

col1  col3  col2_x  col2_y  col2_z
0     1  3000       1       0       0
1     0    20       0       1       0
2     1  3000       1       0       0
3     0   400       0       0       1

<div   dir='rtl'>
گاهی ممکن است تمایل داشته باشیم که دامنۀ ویژگی‌ در داده‌ها را
    <code>scale</code> کنیم. مثلا از دامنۀ ۱ تا ۱۰۰ به ۰ تا ۱ یا هر دامنۀ دیگری. برای این کار از <code>MinMaxScaler</code> استفاده می‌کنیم.
</div>

In [42]:
ary_int

array([ 71,  50, -86,  64, -90, -78, -78,   3, -63, -21])

In [43]:
mm_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
mm_scaler.fit([ary_int])

MinMaxScaler()

In [44]:
print(mm_scaler.fit_transform([ary_int]), '!انگار چیزی اشتباه شده')

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] !انگار چیزی اشتباه شده


In [45]:
np.expand_dims(ary_int, axis=1)

array([[ 71],
       [ 50],
       [-86],
       [ 64],
       [-90],
       [-78],
       [-78],
       [  3],
       [-63],
       [-21]])

<div   dir='rtl'>
        همان‌طور که مشاهده می‌شود خط آخر چیزی نیست که انتظار آن را داشتیم. دلیل این امر آن است که ورودی باید
    یک ماتریس <code>(n,1)</code> باشد. برای این کار کافیست ورودی را به صورت <code>numpy array</code> تعریف کنیم.
</div>

In [46]:
print(mm_scaler.fit_transform(np.expand_dims(ary_int, axis=1)))

[[1.        ]
 [0.86956522]
 [0.02484472]
 [0.95652174]
 [0.        ]
 [0.07453416]
 [0.07453416]
 [0.57763975]
 [0.16770186]
 [0.42857143]]


In [47]:
# از این راه هم می توان کار بالا را انجام داد
mm_scaler.fit_transform(ary_int.reshape(-1, 1))

array([[1.        ],
       [0.86956522],
       [0.02484472],
       [0.95652174],
       [0.        ],
       [0.07453416],
       [0.07453416],
       [0.57763975],
       [0.16770186],
       [0.42857143]])

In [48]:
mm_scaler = preprocessing.MinMaxScaler(feature_range=(0, 10))
mm_scaler.fit_transform(ary_int.reshape(-1, 1))

array([[10.        ],
       [ 8.69565217],
       [ 0.2484472 ],
       [ 9.56521739],
       [ 0.        ],
       [ 0.74534161],
       [ 0.74534161],
       [ 5.77639752],
       [ 1.67701863],
       [ 4.28571429]])

In [49]:
X_train = np.array([[ 1., -1.,  2.],
                   [ 2.,  0.,  0.],
                   [ 0.,  1., -1.]])
X_scaled = preprocessing.scale(X_train)

X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [50]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [51]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [52]:
df

col1 col2  col3
0     1    x  3000
1     0    y    20
2     1    x  3000
3     0    z   400

In [53]:
numeric_df = df.apply(lambda x: np.log10(x) if np.issubdtype(x.dtype, np.number) else x)
numeric_df

c:\users\mohammad\appdata\local\programs\python\python39\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)


col1 col2      col3
0   0.0    x  3.477121
1  -inf    y  1.301030
2   0.0    x  3.477121
3  -inf    z  2.602060

In [54]:
df

col1 col2  col3
0     1    x  3000
1     0    y    20
2     1    x  3000
3     0    z   400

In [55]:
numeric_df['col3'] = df['col3'].apply(lambda x: np.log10(x))

In [56]:
df[df.duplicated(keep=False)]

col1 col2  col3
0     1    x  3000
2     1    x  3000

In [57]:
df.duplicated().sum()

1

In [58]:
df[df.duplicated() == False]

col1 col2  col3
0     1    x  3000
1     0    y    20
3     0    z   400

In [59]:
tmp = df[['col1', 'col2']]
tmp

col1 col2
0     1    x
1     0    y
2     1    x
3     0    z

In [60]:
tmp = df.drop(['col3'], axis=1)
tmp

col1 col2
0     1    x
1     0    y
2     1    x
3     0    z

In [61]:
tmp = df.drop(0, axis=0)
tmp

col1 col2  col3
1     0    y    20
2     1    x  3000
3     0    z   400

In [62]:
arr = np.array([1, 7, 5, 4, 6, 3, 11, 17, 51, 14, 61, 23])

In [63]:
arr

array([ 1,  7,  5,  4,  6,  3, 11, 17, 51, 14, 61, 23])

In [64]:
pd.cut(arr, 4)

[(0.94, 16.0], (0.94, 16.0], (0.94, 16.0], (0.94, 16.0], (0.94, 16.0], ..., (16.0, 31.0], (46.0, 61.0], (0.94, 16.0], (46.0, 61.0], (16.0, 31.0]]
Length: 12
Categories (4, interval[float64, right]): [(0.94, 16.0] < (16.0, 31.0] < (31.0, 46.0] < (46.0, 61.0]]

In [65]:
pd.cut(np.array([1, 7, 5, 4, 6, 3]),3, labels=["bad", "medium", "good"])

['bad', 'good', 'medium', 'medium', 'good', 'bad']
Categories (3, object): ['bad' < 'medium' < 'good']

In [66]:
df

col1 col2  col3
0     1    x  3000
1     0    y    20
2     1    x  3000
3     0    z   400

In [67]:
pd.cut(df['col3'], 3)

0    (2006.667, 3000.0]
1     (17.02, 1013.333]
2    (2006.667, 3000.0]
3     (17.02, 1013.333]
Name: col3, dtype: category
Categories (3, interval[float64, right]): [(17.02, 1013.333] < (1013.333, 2006.667] < (2006.667, 3000.0]]

In [68]:
pd.cut(df['col3'], 3, labels=False)

0    2
1    0
2    2
3    0
Name: col3, dtype: int64